[package]
name = "ofs-radio"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
glam.workspace = true
ofs-core.workspace = true
ofs-rf.workspace = true
rand.workspace = true
rand_chacha.workspace = true

[dev-dependencies]
proptest.workspace = true
