[package]
name = "ofs-sim"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ofs-core.workspace = true
ofs-physics.workspace = true
ofs-electrical.workspace = true
ofs-sensors.workspace = true
ofs-config.workspace = true
ofs-fc.workspace = true
ofs-radio.workspace = true
ofs-proto.workspace = true
glam.workspace = true
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
ofs-client = { path = "../ofs-client" }
tempfile.workspace = true
