# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ofs.v1 import sim_pb2 as ofs_dot_v1_dot_sim__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ofs/v1/sim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimStub:
    """Headless simulator control. Lockstep only in protocol version 1.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/ofs.v1.Sim/Handshake',
                request_serializer=ofs_dot_v1_dot_sim__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=ofs_dot_v1_dot_sim__pb2.HandshakeReply.FromString,
                _registered_method=True)
        self.Load = channel.unary_unary(
                '/ofs.v1.Sim/Load',
                request_serializer=ofs_dot_v1_dot_sim__pb2.LoadRequest.SerializeToString,
                response_deserializer=ofs_dot_v1_dot_sim__pb2.LoadReply.FromString,
                _registered_method=True)
        self.SetSticks = channel.unary_unary(
                '/ofs.v1.Sim/SetSticks',
                request_serializer=ofs_dot_v1_dot_sim__pb2.Sticks.SerializeToString,
                response_deserializer=ofs_dot_v1_dot_sim__pb2.Empty.FromString,
                _registered_method=True)
        self.Run = channel.unary_unary(
                '/ofs.v1.Sim/Run',
                request_serializer=ofs_dot_v1_dot_sim__pb2.RunRequest.SerializeToString,
                response_deserializer=ofs_dot_v1_dot_sim__pb2.State.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/ofs.v1.Sim/GetState',
                request_serializer=ofs_dot_v1_dot_sim__pb2.Empty.SerializeToString,
                response_deserializer=ofs_dot_v1_dot_sim__pb2.State.FromString,
                _registered_method=True)
        self.Unload = channel.unary_unary(
                '/ofs.v1.Sim/Unload',
                request_serializer=ofs_dot_v1_dot_sim__pb2.Empty.SerializeToString,
                response_deserializer=ofs_dot_v1_dot_sim__pb2.Empty.FromString,
                _registered_method=True)


class SimServicer:
    """Headless simulator control. Lockstep only in protocol version 1.
    """

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSticks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=ofs_dot_v1_dot_sim__pb2.HandshakeRequest.FromString,
                    response_serializer=ofs_dot_v1_dot_sim__pb2.HandshakeReply.SerializeToString,
            ),
            'Load': grpc.unary_unary_rpc_method_handler(
                    servicer.Load,
                    request_deserializer=ofs_dot_v1_dot_sim__pb2.LoadRequest.FromString,
                    response_serializer=ofs_dot_v1_dot_sim__pb2.LoadReply.SerializeToString,
            ),
            'SetSticks': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSticks,
                    request_deserializer=ofs_dot_v1_dot_sim__pb2.Sticks.FromString,
                    response_serializer=ofs_dot_v1_dot_sim__pb2.Empty.SerializeToString,
            ),
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=ofs_dot_v1_dot_sim__pb2.RunRequest.FromString,
                    response_serializer=ofs_dot_v1_dot_sim__pb2.State.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=ofs_dot_v1_dot_sim__pb2.Empty.FromString,
                    response_serializer=ofs_dot_v1_dot_sim__pb2.State.SerializeToString,
            ),
            'Unload': grpc.unary_unary_rpc_method_handler(
                    servicer.Unload,
                    request_deserializer=ofs_dot_v1_dot_sim__pb2.Empty.FromString,
                    response_serializer=ofs_dot_v1_dot_sim__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ofs.v1.Sim', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ofs.v1.Sim', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sim:
    """Headless simulator control. Lockstep only in protocol version 1.
    """

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ofs.v1.Sim/Handshake',
            ofs_dot_v1_dot_sim__pb2.HandshakeRequest.SerializeToString,
            ofs_dot_v1_dot_sim__pb2.HandshakeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ofs.v1.Sim/Load',
            ofs_dot_v1_dot_sim__pb2.LoadRequest.SerializeToString,
            ofs_dot_v1_dot_sim__pb2.LoadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSticks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ofs.v1.Sim/SetSticks',
            ofs_dot_v1_dot_sim__pb2.Sticks.SerializeToString,
            ofs_dot_v1_dot_sim__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ofs.v1.Sim/Run',
            ofs_dot_v1_dot_sim__pb2.RunRequest.SerializeToString,
            ofs_dot_v1_dot_sim__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ofs.v1.Sim/GetState',
            ofs_dot_v1_dot_sim__pb2.Empty.SerializeToString,
            ofs_dot_v1_dot_sim__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ofs.v1.Sim/Unload',
            ofs_dot_v1_dot_sim__pb2.Empty.SerializeToString,
            ofs_dot_v1_dot_sim__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
